// ─── VNDC Campus Contract ABIs ───
// Minimal ABIs with only the functions needed for frontend interaction

export const VNDC_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "function burn(uint256 amount)",
  "function burnFrom(address account, uint256 amount)",
  "function pause()",
  "function unpause()",
  "function isPaused() view returns (bool)",
  "function isMinter(address account) view returns (bool)",
  "function isBurner(address account) view returns (bool)",
  "function addMinter(address account)",
  "function removeMinter(address account)",
  "function addBurner(address account)",
  "function removeBurner(address account)",
  "function getTokenInfo() view returns (string name, string symbol, uint8 decimals, uint256 totalSupply)",
  "function permit(address owner, address spender, uint256 amount, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event TokenMinted(address indexed to, uint256 amount)",
  "event TokenBurned(address indexed from, uint256 amount)",
  "event MinterAdded(address indexed account)",
  "event MinterRemoved(address indexed account)",
] as const;

export const REGISTRY_ABI = [
  "function registerUser(address user, string name, bytes32 role)",
  "function updateProfile(address user, string newName, string metadataUri)",
  "function getUserProfile(address user) view returns (tuple(address userAddress, string name, bytes32 role, string metadataUri, uint256 registeredAt, bool exists))",
  "function userExists(address user) view returns (bool)",
  "function getUserRole(address user) view returns (bytes32)",
  "function getUserName(address user) view returns (string)",
  "function changeUserRole(address user, bytes32 newRole)",
  "function getUsersByRole(bytes32 role) view returns (address[])",
  "function getRoleMemberCount(bytes32 role) view returns (uint256)",
  "function getTotalUsers() view returns (uint256)",
  "function getAllUsers() view returns (address[])",
  "function registerUsersBatch(address[] users, string[] names, bytes32[] roles)",
  "function getRegistryStats() view returns (uint256 totalUsers, uint256 totalAdmins, uint256 totalTeachers, uint256 totalStudents)",
  "event UserRegistered(address indexed user, bytes32 role)",
  "event UserUpdated(address indexed user, string newName)",
  "event UserRoleChanged(address indexed user, bytes32 oldRole, bytes32 newRole)",
] as const;

export const ACCESS_CONTROL_ABI = [
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function grantRole(bytes32 role, address account)",
  "function revokeRole(bytes32 role, address account)",
  "function isAuthorized(address account) view returns (bool)",
  "function getRoles(address account) view returns (bytes32[])",
  "function getRoleMembers(bytes32 role) view returns (address[])",
  "function getRoleMemberCount(bytes32 role) view returns (uint256)",
  "function isAdmin(address account) view returns (bool)",
  "function isTeacher(address account) view returns (bool)",
  "function isStudent(address account) view returns (bool)",
  "function isMerchant(address account) view returns (bool)",
  "function isIssuer(address account) view returns (bool)",
  "function grantRoleBatch(bytes32 role, address[] accounts)",
  "function revokeRoleBatch(bytes32 role, address[] accounts)",
  "function getAccessStats() view returns (uint256 adminCount, uint256 teacherCount, uint256 studentCount, uint256 merchantCount)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed grantedBy)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed revokedBy)",
] as const;

export const CREDENTIAL_VERIFICATION_ABI = [
  "function issueCredential(address student, string name, string level, uint256 expirationDays, string ipfsMetadata) returns (uint256 tokenId)",
  "function verifyCredential(uint256 tokenId) view returns (bool valid, string name, string level)",
  "function revokeCredential(uint256 tokenId)",
  "function getCredentialsByUser(address user) view returns (uint256[])",
  "function getCredential(uint256 tokenId) view returns (tuple(string name, string level, address issuer, uint256 issuedAt, uint256 expiresAt, bool revoked, string ipfsMetadata))",
  "function isCredentialValid(uint256 tokenId) view returns (bool)",
  "function addIssuer(address issuer)",
  "function removeIssuer(address issuer)",
  "function isIssuer(address issuer) view returns (bool)",
  "function getActiveCredentialsByUser(address user) view returns (uint256[])",
  "function getStats() view returns (uint256 totalIssuers, uint256 totalCredentialVariants)",
  "event CredentialIssued(uint256 indexed tokenId, address indexed student, string name, string level, address indexed issuer)",
  "event CredentialRevoked(uint256 indexed tokenId, address indexed revoker)",
] as const;

export const CREDENTIAL_NFT_ABI = [
  "function mint(address to, string credentialURI) returns (uint256)",
  "function burn(uint256 tokenId)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function tokensOfOwner(address owner) view returns (uint256[])",
  "function exists(uint256 tokenId) view returns (bool)",
  "function balanceOf(address owner) view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
] as const;

export const ACADEMIC_REWARD_ABI = [
  "function setRewardTier(uint256 tierId, string name, uint256 minGPA, uint256 vncdAmount, uint256 badgeTokenId)",
  "function awardStudent(address student, uint256 gpa) returns (uint256 rewardId)",
  "function claimReward(uint256 rewardId)",
  "function getStudentRewards(address student) view returns (uint256[])",
  "function getReward(uint256 rewardId) view returns (tuple(address student, uint256 gpa, uint256 tierId, uint256 issuedAt, bool claimed))",
  "function getRewardTier(uint256 tierId) view returns (tuple(string name, uint256 minGPA, uint256 vncdAmount, uint256 badgeTokenId, bool active))",
  "function deactivateTier(uint256 tierId)",
  "function getClaimedRewards(address student) view returns (uint256[])",
  "function getStats() view returns (uint256 totalAwarded, uint256 totalClaimed)",
  "function addIssuer(address issuer)",
  "function removeIssuer(address issuer)",
  "function isIssuer(address issuer) view returns (bool)",
  "event RewardTierSet(uint256 indexed tierId, string name, uint256 minGPA, uint256 vncdAmount)",
  "event StudentAwarded(uint256 indexed rewardId, address indexed student, uint256 gpa, uint256 tierId)",
  "event RewardClaimed(uint256 indexed rewardId, address indexed student)",
] as const;

export const ACADEMIC_BADGE_NFT_ABI = [
  "function mint(address to, uint256 badgeId, uint256 amount)",
  "function burn(address account, uint256 badgeId, uint256 amount)",
  "function getBalances(address account) view returns (uint256[])",
  "function createBadge(string uri) returns (uint256 badgeId)",
  "function uri(uint256 badgeId) view returns (string)",
  "function badgeExists(uint256 badgeId) view returns (bool)",
  "function hasBadge(address user, uint256 badgeId) view returns (bool)",
  "function balanceOf(address account, uint256 id) view returns (uint256)",
] as const;

export const PAYMENT_PROCESSOR_ABI = [
  "function processPayment(address merchant, uint256 amount, string paymentMethod) returns (uint256 paymentId)",
  "function refundPayment(uint256 paymentId, string reason)",
  "function linkWallet(string paymentMethod, string walletId)",
  "function unlinkWallet(string paymentMethod)",
  "function addPaymentMethod(string name, address tokenAddress, uint256 minAmount, uint256 maxAmount)",
  "function removePaymentMethod(string paymentMethod)",
  "function getPaymentRecord(uint256 paymentId) view returns (tuple(uint256 paymentId, address student, address merchant, uint256 amount, string paymentMethod, uint256 timestamp, bool isRefunded, uint256 refundAmount, string refundReason, uint256 refundTimestamp))",
  "function getStudentPayments(address student) view returns (tuple(uint256 paymentId, address student, address merchant, uint256 amount, string paymentMethod, uint256 timestamp, bool isRefunded, uint256 refundAmount, string refundReason, uint256 refundTimestamp)[])",
  "function getMerchantPayments(address merchant) view returns (tuple(uint256 paymentId, address student, address merchant, uint256 amount, string paymentMethod, uint256 timestamp, bool isRefunded, uint256 refundAmount, string refundReason, uint256 refundTimestamp)[])",
  "function isPaymentMethodSupported(string paymentMethod) view returns (bool)",
  "function getTotalStudentPayments(address student) view returns (uint256)",
  "function getTotalMerchantRevenue(address merchant) view returns (uint256)",
  "function getTotalPaymentCount() view returns (uint256)",
  "event PaymentProcessed(uint256 indexed paymentId, address indexed student, address indexed merchant, uint256 amount, string paymentMethod, uint256 timestamp)",
  "event PaymentRefunded(uint256 indexed paymentId, address indexed student, uint256 refundAmount, string reason, uint256 timestamp)",
] as const;

export const MERCHANT_REGISTRY_ABI = [
  "function registerMerchant(string name, string category, string contactEmail, string contactPhone) returns (address)",
  "function updateMerchant(address merchant, string name, string category, string contactEmail, string contactPhone)",
  "function approveMerchant(address merchant)",
  "function rejectMerchant(address merchant, string reason)",
  "function deactivateMerchant(address merchant)",
  "function reactivateMerchant(address merchant)",
  "function setCommissionRate(address merchant, uint256 commissionRate)",
  "function getMerchant(address merchant) view returns (tuple(address merchantAddress, string name, string category, string contactEmail, string contactPhone, bool isApproved, bool isActive, uint256 commissionRate, uint256 totalTransactions, uint256 totalRevenue, uint256 registrationDate, uint256 approvalDate))",
  "function isApprovedMerchant(address merchant) view returns (bool)",
  "function isMerchantActive(address merchant) view returns (bool)",
  "function getTotalMerchants() view returns (uint256)",
  "function getTotalApprovedMerchants() view returns (uint256)",
  "event MerchantRegistered(address indexed merchant, string name, string category, uint256 timestamp)",
  "event MerchantApproved(address indexed merchant, uint256 timestamp)",
] as const;

export const STUDENT_RECORD_MANAGER_ABI = [
  "function createRecord(string name, string studentId, string transcript) returns (uint256 recordId)",
  "function addGrade(uint256 recordId, string subject, uint256 grade, uint256 credits)",
  "function completeSemester(uint256 recordId, uint256 semesterIndex)",
  "function verifyRecord(uint256 recordId)",
  "function issueTranscript(uint256 recordId, string ipfsHash)",
  "function updateRecord(uint256 recordId, string name, string transcript)",
  "function getRecord(uint256 recordId) view returns (tuple(uint256 recordId, address student, string name, string studentId, uint256 enrollmentDate, uint256 totalCredits, uint256 cumulativeGpa, tuple(uint256 semesterIndex, tuple(string subject, uint256 grade, uint256 credits, uint256 timestamp)[] grades, uint256 gpa, uint256 totalCredits, uint256 timestamp, bool isCompleted)[] semesters, bool isVerified, address verifier, uint256 verificationDate, string transcriptIPFS))",
  "function getStudentRecords(address student) view returns (uint256[])",
  "function getSemesterGPA(uint256 recordId, uint256 semesterIndex) view returns (uint256)",
  "function getCumulativeGPA(uint256 recordId) view returns (uint256)",
  "function isRecordVerified(uint256 recordId) view returns (bool)",
  "function getTotalCredits(uint256 recordId) view returns (uint256)",
  "function getTotalRecords() view returns (uint256)",
  "function authorizeVerifier(address verifier)",
  "function revokeVerifier(address verifier)",
  "function isAuthorizedVerifier(address verifier) view returns (bool)",
  "event RecordCreated(address indexed student, uint256 recordId, string transcript, uint256 timestamp)",
  "event GradeAdded(address indexed student, uint256 recordId, string subject, uint256 grade, uint256 credits, uint256 timestamp)",
  "event SemesterCompleted(address indexed student, uint256 recordId, uint256 semesterIndex, uint256 gpa, uint256 timestamp)",
  "event RecordVerified(address indexed student, uint256 recordId, address verifier, uint256 timestamp)",
] as const;

export const STUDENT_DAO_ABI = [
  "function createProposal(string title, string description, string proposalType, bytes callData) returns (uint256 proposalId)",
  "function vote(uint256 proposalId, bool support)",
  "function executeProposal(uint256 proposalId)",
  "function cancelProposal(uint256 proposalId)",
  "function addMember(address member, uint256 votingPower)",
  "function removeMember(address member)",
  "function updateVotingPower(address member, uint256 newVotingPower)",
  "function setVotingPeriod(uint256 durationInSeconds)",
  "function setQuorum(uint256 quorumPercentage)",
  "function getProposal(uint256 proposalId) view returns (tuple(uint256 proposalId, address proposer, string title, string description, uint256 createdAt, uint256 votesFor, uint256 votesAgainst, bool executed, bool cancelled, uint256 votingEndTime, string proposalType, bytes callData))",
  "function getMember(address member) view returns (tuple(address memberAddress, uint256 votingPower, uint256 joinDate, bool isActive, uint256 proposalsCreated, uint256 votesParticipated))",
  "function isMember(address member) view returns (bool)",
  "function getVotingPower(address member) view returns (uint256)",
  "function hasVoted(uint256 proposalId, address member) view returns (bool)",
  "function getTotalMembers() view returns (uint256)",
  "function getTotalProposals() view returns (uint256)",
  "function getVotingPeriod() view returns (uint256)",
  "function isProposalApproved(uint256 proposalId) view returns (bool)",
  "function getTotalVotingPower() view returns (uint256)",
  "function getActiveProposals() view returns (uint256[])",
  "function getProposalVotes(uint256 proposalId) view returns (uint256 votesFor, uint256 votesAgainst)",
  "event ProposalCreated(uint256 indexed proposalId, address indexed proposer, string title, string description, uint256 timestamp)",
  "event Voted(uint256 indexed proposalId, address indexed voter, bool support, uint256 weight)",
  "event ProposalExecuted(uint256 indexed proposalId, uint256 timestamp)",
  "event ProposalCancelled(uint256 indexed proposalId, uint256 timestamp)",
  "event MemberJoined(address indexed member, uint256 votingPower, uint256 timestamp)",
] as const;

export const GOVERNANCE_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "function delegate(address delegatee)",
  "function delegates(address account) view returns (address)",
  "function getVotes(address account) view returns (uint256)",
  "function bulkMint(address[] recipients, uint256[] amounts)",
] as const;

export const STUDENT_ID_ABI = [
  "function issueStudentID(address student, string studentName, string program, uint256 enrollmentDate, string metadataURI) returns (uint256 tokenId)",
  "function suspendStudentID(uint256 tokenId, string reason)",
  "function revokeStudentID(uint256 tokenId, string reason)",
  "function reactivateStudentID(uint256 tokenId)",
  "function updateMetadataURI(uint256 tokenId, string newURI)",
  "function authorizeVerifier(address verifier)",
  "function revokeVerifier(address verifier)",
  "function getStudentInfo(uint256 tokenId) view returns (address studentAddr, string studentName, string program, uint256 enrollmentDate, uint256 issuedAt, bool isSuspended, bool isRevoked)",
  "function getStudentIDDetails(uint256 tokenId) view returns (string metadataURI, string suspensionReason, string revocationReason)",
  "function getActiveStudentIDs(address student) view returns (uint256[])",
  "function isActiveStudentID(uint256 tokenId) view returns (bool)",
  "function isAuthorizedVerifier(address verifier) view returns (bool)",
  "function getTotalStudentIDs() view returns (uint256)",
  "function getTotalActiveStudentIDs() view returns (uint256)",
  "function getTotalSuspendedStudentIDs() view returns (uint256)",
  "function getTotalRevokedStudentIDs() view returns (uint256)",
  "function balanceOf(address owner) view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "event StudentIDIssued(address indexed student, uint256 indexed tokenId, uint256 issuedAt)",
  "event StudentIDSuspended(uint256 indexed tokenId, string reason, uint256 suspendedAt)",
  "event StudentIDRevoked(uint256 indexed tokenId, string reason, uint256 revokedAt)",
  "event StudentIDReactivated(uint256 indexed tokenId, uint256 reactivatedAt)",
] as const;

export const SCHOLARSHIP_MANAGER_ABI = [
  "function createScholarship(string name, string description, uint256 totalAmount, uint256 maxAwards, string requirements, uint256 duration) returns (uint256)",
  "function depositFunds(uint256 scholarshipId, uint256 amount)",
  "function awardScholarship(uint256 scholarshipId, address student, uint256 amount)",
  "function claimScholarship(uint256 scholarshipId)",
  "function updateScholarshipStatus(uint256 scholarshipId, string newStatus)",
  "function withdrawFunds(uint256 scholarshipId, uint256 amount)",
  "function addFundingEntity(address fundingEntity)",
  "function removeFundingEntity(address fundingEntity)",
  "function getScholarshipInfo(uint256 scholarshipId) view returns (string name, string description, address funder, uint256 totalAmount, uint256 distributedAmount, uint256 maxAwards, uint256 awardsGiven, uint256 createdAt, uint256 endsAt, string status)",
  "function getScholarshipRequirements(uint256 scholarshipId) view returns (string)",
  "function getStudentScholarships(address student) view returns (uint256[])",
  "function isScholarshipOpen(uint256 scholarshipId) view returns (bool)",
  "function getTotalScholarships() view returns (uint256)",
  "function getTotalFundsInScholarships() view returns (uint256)",
  "function getTotalFundsDistributed() view returns (uint256)",
  "function getAvailableFunds(uint256 scholarshipId) view returns (uint256)",
  "event ScholarshipCreated(uint256 indexed scholarshipId, string name, uint256 totalAmount, uint256 maxAwards, address funder)",
  "event StudentAwarded(uint256 indexed scholarshipId, address indexed student, uint256 amount, uint256 awardedAt)",
  "event ScholarshipClaimed(uint256 indexed scholarshipId, address indexed student, uint256 amount, uint256 claimedAt)",
] as const;

export const JOB_BOARD_ABI = [
  "function registerEmployer(string companyName, string companyURI)",
  "function postJob(string title, string description, string category, string location, string jobType, uint256 minSalary, uint256 maxSalary, string requiredSkills) returns (uint256 jobId)",
  "function applyForJob(uint256 jobId, string coverLetter) returns (uint256 applicationId)",
  "function updateApplicationStatus(uint256 applicationId, string status)",
  "function updateJobStatus(uint256 jobId, string status)",
  "function submitReview(uint256 jobId, uint256 rating, string comment)",
  "function getJobDetails(uint256 jobId) view returns (string title, string description, address employer, string category, string location, string jobType, uint256 minSalary, uint256 maxSalary, string requiredSkills, string status, uint256 postedAt, uint256 applicationCount)",
  "function getApplicationDetails(uint256 applicationId) view returns (address applicant, uint256 jobId, string coverLetter, string status, uint256 submittedAt)",
  "function getEmployerInfo(address employer) view returns (string companyName, string companyURI, uint256 jobsPosted, uint256 registeredAt)",
  "function getJobApplications(uint256 jobId) view returns (uint256[])",
  "function getStudentApplications(address student) view returns (uint256[])",
  "function getEmployerJobs(address employer) view returns (uint256[])",
  "function isRegisteredEmployer(address employer) view returns (bool)",
  "function getTotalJobsPosted() view returns (uint256)",
  "function getTotalApplications() view returns (uint256)",
  "function getTotalEmployers() view returns (uint256)",
  "function getJobsByCategory(string category) view returns (uint256[])",
  "event JobPosted(uint256 indexed jobId, string title, address indexed employer, uint256 postedAt)",
  "event ApplicationSubmitted(uint256 indexed jobId, address indexed applicant, uint256 applicationId, uint256 submittedAt)",
  "event ApplicationStatusUpdated(uint256 indexed applicationId, string status)",
] as const;

export const EXTRACURRICULAR_REWARD_ABI = [
  "function registerActivity(string name, string description, uint256 rewardAmount, uint256 badgeTokenId, uint256 maxClaimsPerStudent) returns (uint256)",
  "function logActivity(address student, uint256 activityId, string metadata) returns (uint256)",
  "function claimActivity(uint256 recordId)",
  "function getActivities() view returns (uint256[])",
  "function getStudentActivities(address student) view returns (uint256[])",
  "function getActivity(uint256 activityId) view returns (tuple(string name, string description, uint256 rewardAmount, uint256 badgeTokenId, uint256 maxClaimsPerStudent, bool active, uint256 createdAt))",
  "function getActivityRecord(uint256 recordId) view returns (tuple(address student, uint256 activityId, uint256 timestamp, bool rewarded, string metadata))",
  "function getClaimCount(address student, uint256 activityId) view returns (uint256)",
  "function getCompletedActivities(address student) view returns (uint256[])",
  "function deactivateActivity(uint256 activityId)",
  "function addIssuer(address issuer)",
  "function removeIssuer(address issuer)",
  "function isIssuer(address addr) view returns (bool)",
  "function createActivityBadge(string name, string uri) returns (uint256)",
  "function pause()",
  "function unpause()",
  "event ActivityRegistered(uint256 indexed activityId, string name, uint256 rewardAmount)",
  "event ActivityLogged(address indexed student, uint256 indexed activityId, uint256 recordId)",
  "event ActivityClaimed(uint256 indexed recordId, address indexed student)",
] as const;

export const CERTIFICATION_SYSTEM_ABI = [
  "function createCertificateType(string name, string description, string metadataURI) returns (uint256)",
  "function issueCertificate(address student, uint256 certificateTypeId, string metadataURI, uint256 expiryDate) returns (uint256)",
  "function revokeCertificate(uint256 tokenId, string reason)",
  "function verifyCertificate(uint256 tokenId)",
  "function authorizeIssuer(address issuer, uint256[] certificateTypeIds)",
  "function revokeIssuer(address issuer)",
  "function authorizeVerifier(address verifier)",
  "function revokeVerifier(address verifier)",
  "function getCertificateType(uint256 certificateTypeId) view returns (string name, string description, string metadataURI, uint256 createdAt, uint256 totalIssued)",
  "function getCertificateDetails(uint256 tokenId) view returns (address student, uint256 certificateTypeId, uint256 issuedAt, uint256 expiryDate, bool isRevoked, bool isVerified, string metadataURI)",
  "function getStudentCertificates(address student) view returns (uint256[])",
  "function isCertificateValid(uint256 tokenId) view returns (bool)",
  "function isCertificateExpired(uint256 tokenId) view returns (bool)",
  "function isAuthorizedIssuer(address issuer) view returns (bool)",
  "function isAuthorizedVerifier(address verifier) view returns (bool)",
  "function getTotalCertificateTypes() view returns (uint256)",
  "function getTotalCertificatesIssued() view returns (uint256)",
  "function getTotalActiveCertificates() view returns (uint256)",
  "function getTotalRevokedCertificates() view returns (uint256)",
  "function getTotalVerifiedCertificates() view returns (uint256)",
  "event CertificateIssued(uint256 indexed tokenId, address indexed student, uint256 certificateTypeId)",
  "event CertificateRevoked(uint256 indexed tokenId, string reason)",
  "event CertificateVerified(uint256 indexed tokenId, address indexed verifier)",
] as const;

export const ALUMNI_REGISTRY_ABI = [
  "function registerAlumni(string name, string program, uint256 graduationYear, string profileURI)",
  "function updateProfile(string field, string value)",
  "function updateStatus(string status)",
  "function createEvent(string name, string description, uint256 eventDate, string location) returns (uint256)",
  "function registerForEvent(uint256 eventId)",
  "function createMentorship(address mentee, uint256 duration) returns (uint256)",
  "function connectWithAlumni(address otherAlumni)",
  "function makeDonation(uint256 amount, string purpose)",
  "function authorizeMentor(address mentor)",
  "function revokeMentor(address mentor)",
  "function getAlumniProfile(address alumni) view returns (string name, string program, uint256 graduationYear, string status, uint256 registeredAt, string profileURI)",
  "function getEventInfo(uint256 eventId) view returns (string name, string description, uint256 eventDate, string location, address organizer, uint256 registrationCount)",
  "function getConnections(address alumni) view returns (address[])",
  "function getMentorshipInfo(uint256 mentorshipId) view returns (address mentor, address mentee, uint256 startDate, uint256 endDate, bool isActive)",
  "function isRegisteredAlumni(address alumni) view returns (bool)",
  "function getTotalAlumni() view returns (uint256)",
  "function getTotalEvents() view returns (uint256)",
  "function getTotalMentorships() view returns (uint256)",
  "function getTotalDonations() view returns (uint256)",
  "function getTotalDonationAmount() view returns (uint256)",
  "event AlumniRegistered(address indexed alumni, string name, uint256 graduationYear)",
  "event EventCreated(uint256 indexed eventId, string name, uint256 eventDate)",
  "event MentorRegistered(address indexed mentor)",
  "event DonationReceived(address indexed donor, uint256 amount, string purpose)",
] as const;

export const REPUTATION_BADGE_ABI = [
  "function createBadgeType(string name, string description, uint256 requiredPoints, string category, string iconURI) returns (uint256)",
  "function awardBadge(address user, uint256 badgeTypeId)",
  "function revokeBadge(address user, uint256 badgeTypeId)",
  "function addReputationPoints(address user, uint256 points, string reason)",
  "function deductReputationPoints(address user, uint256 points, string reason)",
  "function unlockAchievement(address user, string achievement)",
  "function authorizeBadgeIssuer(address issuer)",
  "function revokeBadgeIssuer(address issuer)",
  "function authorizePointsEditor(address editor)",
  "function revokePointsEditor(address editor)",
  "function getUserReputationPoints(address user) view returns (uint256)",
  "function getUserTier(address user) view returns (uint256)",
  "function getUserBadges(address user) view returns (uint256[])",
  "function hasBadge(address user, uint256 badgeTypeId) view returns (bool)",
  "function getBadgeTypeInfo(uint256 badgeTypeId) view returns (string name, string description, uint256 requiredPoints, string category, string iconURI, uint256 totalAwarded)",
  "function getUserAchievements(address user) view returns (string[])",
  "function getReputationHistory(address user) view returns (uint256[] points, string[] reasons, uint256[] timestamps)",
  "function getBadgeHistory(address user) view returns (uint256[] badgeTypeIds, uint256[] awardedAt, bool[] isActive)",
  "function getTotalBadgeTypes() view returns (uint256)",
  "function getTotalUsersWithReputation() view returns (uint256)",
  "function getLeaderboard(uint256 limit) view returns (address[] users, uint256[] points)",
  "function getTierInfo(uint256 tier) view returns (uint256 minPoints, uint256 maxPoints, string name)",
  "function isBadgeIssuer(address issuer) view returns (bool)",
  "function isPointsEditor(address editor) view returns (bool)",
  "event BadgeAwarded(address indexed user, uint256 badgeTypeId)",
  "event BadgeRevoked(address indexed user, uint256 badgeTypeId)",
  "event ReputationPointsAdded(address indexed user, uint256 points, string reason)",
  "event TierUpdated(address indexed user, uint256 newTier)",
] as const;

export const INTERNSHIP_MANAGER_ABI = [
  "function createInternship(string title, string description, uint256 startDate, uint256 endDate, bool mentorRequired, uint256 minGPA, uint256 maxPositions) returns (uint256)",
  "function applyForInternship(uint256 internshipId, string motivationLetter) returns (uint256)",
  "function extendOffer(uint256 applicationId, uint256 stipend, uint256 offerValidDays)",
  "function acceptOffer(uint256 applicationId)",
  "function startInternship(uint256 applicationId)",
  "function completeInternship(uint256 applicationId, string certificateURI)",
  "function assignMentor(uint256 applicationId, address mentor)",
  "function evaluatePerformance(uint256 applicationId, uint256 score, string feedback)",
  "function recordMilestone(uint256 applicationId, string milestoneName)",
  "function addRequirement(uint256 internshipId, string requirement)",
  "function getInternshipDetails(uint256 internshipId) view returns (string title, string description, address company, uint256 startDate, uint256 endDate, bool mentorRequired, uint256 minGPA, uint256 maxPositions, uint256 filledPositions, string status)",
  "function getApplicationStatus(uint256 applicationId) view returns (address intern, uint256 internshipId, string status, uint256 submittedAt, uint256 offerExpiry)",
  "function getInternProgress(uint256 applicationId) view returns (address mentor, uint256 performanceScore, uint256 milestonesCount, string evaluationFeedback, string certificateURI)",
  "function getInternshipApplications(uint256 internshipId) view returns (uint256[])",
  "function getInternApplications(address intern) view returns (uint256[])",
  "function getCompanyInternships(address company) view returns (uint256[])",
  "function getTotalInternships() view returns (uint256)",
  "function getTotalInternApplications() view returns (uint256)",
  "function getInternshipRequirements(uint256 internshipId) view returns (string[])",
  "function getInternMilestones(uint256 applicationId) view returns (string[] milestones, uint256[] completedDates)",
  "event InternshipCreated(uint256 indexed internshipId, string title, address indexed company)",
  "event ApplicationSubmitted(uint256 indexed internshipId, address indexed applicant, uint256 applicationId)",
  "event InternshipCompleted(uint256 indexed applicationId, address indexed intern)",
] as const;

export const RESEARCH_PLATFORM_ABI = [
  "function createResearchProject(string title, string description, uint256 startDate, uint256 endDate, uint256 teamSize) returns (uint256)",
  "function addTeamMember(uint256 projectId, address member)",
  "function removeTeamMember(uint256 projectId, address member)",
  "function submitMilestone(uint256 projectId, string milestoneName, string milestoneDescription)",
  "function submitDeliverable(uint256 projectId, string deliverableName, string deliverableHash)",
  "function completeProject(uint256 projectId)",
  "function publishPaper(uint256 projectId, string paperTitle, string paperHash)",
  "function getProjectDetails(uint256 projectId) view returns (string title, string description, address principalInvestigator, uint256 startDate, uint256 endDate, string status, uint256 teamSize)",
  "function getProjectTeam(uint256 projectId) view returns (address[])",
  "function getProjectMilestones(uint256 projectId) view returns (string[] names, string[] descriptions, uint256[] completedDates)",
  "function getProjectDeliverables(uint256 projectId) view returns (string[] names, string[] hashes, uint256[] submittedDates)",
  "function getProjectPapers(uint256 projectId) view returns (string[] titles, string[] hashes, uint256[] publishedDates)",
  "function getResearcherProjects(address researcher) view returns (uint256[])",
  "function getResearcherStats(address researcher) view returns (uint256 totalProjects, uint256 completedProjects, uint256 publishedPapers, uint256 deliverables)",
  "function getTotalProjects() view returns (uint256)",
  "event ProjectCreated(uint256 indexed projectId, string title, address indexed PI)",
  "event TeamMemberAdded(uint256 indexed projectId, address indexed member)",
  "event ProjectCompleted(uint256 indexed projectId)",
  "event PaperPublished(uint256 indexed projectId, string title)",
] as const;

export const AUDITING_SYSTEM_ABI = [
  "function authorizeAuditor(address auditor)",
  "function revokeAuditor(address auditor)",
  "function createAudit(address contractAddress, uint256 criticalIssues, uint256 mediumIssues, uint256 lowIssues) returns (uint256)",
  "function submitReport(uint256 auditId, string reportHash, string findings)",
  "function approveAudit(uint256 auditId)",
  "function rejectAudit(uint256 auditId)",
  "function getAuditDetails(uint256 auditId) view returns (address contractAddress, address auditor, string status, uint256 auditDate, uint256 criticalIssues, uint256 mediumIssues, uint256 lowIssues)",
  "function getAuditReport(uint256 auditId) view returns (string reportHash, string findings, uint256 timestamp)",
  "function getAuditorAudits(address auditor) view returns (uint256[])",
  "function getContractAudits(address contractAddress) view returns (uint256[])",
  "function getTotalAudits() view returns (uint256)",
  "function isAuthorizedAuditor(address auditor) view returns (bool)",
  "event AuditorAuthorized(address indexed auditor)",
  "event AuditCreated(uint256 indexed auditId, address indexed contractAddress, address indexed auditor)",
  "event ReportSubmitted(uint256 indexed auditId, string reportHash)",
  "event AuditApproved(uint256 indexed auditId)",
] as const;

export const DATA_MIGRATION_ABI = [
  "function authorizeSystem(address system)",
  "function createMigrationTask(string dataType, address destinationSystem, uint256 recordCount) returns (uint256)",
  "function completeMigration(uint256 taskId)",
  "function createMapping(string sourceField, string destinationField, string transformationRules) returns (uint256)",
  "function verifyIntegration(uint256 taskId)",
  "function getMigrationStatus(uint256 taskId) view returns (string status, uint256 progress)",
  "function getTotalTasks() view returns (uint256)",
  "event MigrationStarted(uint256 indexed taskId, string dataType, uint256 recordCount)",
  "event MigrationCompleted(uint256 indexed taskId, uint256 timeElapsed)",
  "event MappingCreated(uint256 indexed mappingId, string source, string destination)",
  "event IntegrationVerified(uint256 indexed taskId)",
] as const;

export const ANALYTICS_DASHBOARD_ABI = [
  "function updateMetrics(uint256 totalUsers, uint256 totalTransactions, uint256 totalVolume)",
  "function trackUserActivity(address user, uint256 activityScore, uint256 engagementLevel)",
  "function generateReport(string reportType, string dataHash) returns (uint256)",
  "function getSystemMetrics(uint256 timestamp) view returns (uint256 totalUsers, uint256 totalTransactions, uint256 totalVolume, uint256 metricTimestamp)",
  "function getLatestMetrics() view returns (uint256 totalUsers, uint256 totalTransactions, uint256 totalVolume, uint256 metricTimestamp)",
  "function getUserAnalytics(address user) view returns (uint256 activityScore, uint256 engagementLevel, uint256 lastActivityTime)",
  "function getReportDetails(uint256 reportId) view returns (string reportType, string dataHash, uint256 generatedAt)",
  "function getTotalReports() view returns (uint256)",
  "event MetricsUpdated(uint256 totalUsers, uint256 totalTransactions, uint256 totalVolume)",
  "event UserActivityTracked(address indexed user, uint256 activityScore)",
  "event ReportGenerated(uint256 indexed reportId, string reportType, uint256 timestamp)",
] as const;

export const INTERNAL_EXCHANGE_ABI = [
  "function createOrder(bool isBuyOrder, address tokenOffer, address tokenWant, uint256 amountOffer, uint256 amountWant) returns (uint256 orderId)",
  "function cancelOrder(uint256 orderId)",
  "function fillOrder(uint256 orderId, uint256 amount)",
  "function getOrder(uint256 orderId) view returns (uint256 id, address trader, bool isBuyOrder, address tokenOffer, address tokenWant, uint256 amountOffer, uint256 amountWant, uint256 filled, uint8 status, uint256 createdAt)",
  "function getOpenOrders() view returns (uint256[])",
  "function getUserOrders(address user) view returns (uint256[])",
  "function getOrderBook(address tokenA, address tokenB) view returns (uint256[] buyOrders, uint256[] sellOrders)",
  "function getTradingPair(address tokenA, address tokenB) view returns (uint256 lastPrice, uint256 volume24h, uint256 totalTrades)",
  "function createListing(string title, string description, string category, uint256 price, address paymentToken) returns (uint256 listingId)",
  "function buyListing(uint256 listingId)",
  "function cancelListing(uint256 listingId)",
  "function getListing(uint256 listingId) view returns (address seller, string title, string description, string category, uint256 price, address paymentToken, uint8 status, uint256 createdAt)",
  "function getActiveListings() view returns (uint256[])",
  "function getListingsByCategory(string category) view returns (uint256[])",
  "function getUserListings(address user) view returns (uint256[])",
  "function getTotalOrders() view returns (uint256)",
  "function getTotalListings() view returns (uint256)",
  "function getTotalVolume() view returns (uint256)",
  "event OrderCreated(uint256 indexed orderId, address indexed trader, bool isBuyOrder, address tokenOffer, address tokenWant, uint256 amountOffer, uint256 amountWant)",
  "event OrderFilled(uint256 indexed orderId, address indexed filler, uint256 amount)",
  "event OrderCancelled(uint256 indexed orderId)",
  "event ListingCreated(uint256 indexed listingId, address indexed seller, string title, uint256 price)",
  "event ListingPurchased(uint256 indexed listingId, address indexed buyer, uint256 price)",
  "event ListingCancelled(uint256 indexed listingId)",
] as const;

// ─── Module 019: Marketplace ───
export const MARKETPLACE_ABI = [
  // Admin
  "function owner() view returns (address)",
  "function platformFeeBps() view returns (uint256)",
  "function feeRecipient() view returns (address)",
  "function setPlatformFee(uint256 _feeBps)",
  "function setFeeRecipient(address _recipient)",

  // Shop Management
  "function registerShop(string shopName, string description, string avatarURI, string category) returns (uint256 shopId)",
  "function updateShop(uint256 shopId, string shopName, string description, string avatarURI, string category)",
  "function suspendShop(uint256 shopId, string reason)",
  "function reactivateShop(uint256 shopId)",
  "function getShopInfo(uint256 shopId) view returns (address owner, string shopName, string description, string avatarURI, string category, uint8 status, uint256 totalProducts, uint256 totalSales, uint256 totalRevenue, uint256 totalRating, uint256 reviewCount, uint256 createdAt)",
  "function getShopsByOwner(address owner) view returns (uint256[])",
  "function getTotalShops() view returns (uint256)",
  "function getShopProducts(uint256 shopId) view returns (uint256[])",

  // Product Management
  "function listProduct(uint256 shopId, string name, string description, uint256 price, uint256 stock, string category, string imageURI, string condition) returns (uint256 productId)",
  "function updateProduct(uint256 productId, string name, string description, uint256 price, uint256 stock, string category, string imageURI)",
  "function changeProductStatus(uint256 productId, uint8 newStatus)",
  "function getProduct(uint256 productId) view returns (uint256 id, uint256 shopId, string name, string description, uint256 price, uint256 stock, uint256 sold, string category, string imageURI, string condition, uint8 status, uint256 totalRating, uint256 reviewCount, uint256 createdAt)",
  "function getTotalProducts() view returns (uint256)",
  "function getProductsByCategory(string category) view returns (uint256[])",
  "function searchProducts(string keyword) view returns (uint256[])",

  // Order Management
  "function createOrder(uint256[] productIds, uint256[] quantities, string shippingAddress, string note) returns (uint256 orderId)",
  "function confirmOrder(uint256 orderId)",
  "function shipOrder(uint256 orderId, string trackingCode)",
  "function confirmDelivery(uint256 orderId)",
  "function completeOrder(uint256 orderId)",
  "function cancelOrder(uint256 orderId, string reason)",
  "function requestRefund(uint256 orderId, string reason)",
  "function approveRefund(uint256 orderId)",
  "function getOrder(uint256 orderId) view returns (uint256 id, address buyer, uint256 shopId, uint256 totalAmount, string shippingAddress, string note, string trackingCode, uint8 status, uint256 createdAt, uint256 updatedAt)",
  "function getOrderItems(uint256 orderId) view returns (uint256[] productIds, uint256[] quantities, uint256[] prices)",
  "function getBuyerOrders(address buyer) view returns (uint256[])",
  "function getShopOrders(uint256 shopId) view returns (uint256[])",
  "function getTotalOrders() view returns (uint256)",

  // Reviews
  "function submitReview(uint256 productId, uint256 orderId, uint256 rating, string comment, string imageURI)",
  "function getProductReviews(uint256 productId) view returns (address[] reviewers, uint256[] ratings, string[] comments, string[] imageURIs, uint256[] timestamps)",

  // Wishlist
  "function addToWishlist(uint256 productId)",
  "function removeFromWishlist(uint256 productId)",
  "function getWishlist(address user) view returns (uint256[])",

  // Cart
  "function addToCart(uint256 productId, uint256 quantity)",
  "function removeFromCart(uint256 productId)",
  "function updateCartQuantity(uint256 productId, uint256 quantity)",
  "function getCart(address user) view returns (uint256[] productIds, uint256[] quantities)",
  "function clearCart()",

  // Disputes
  "function openDispute(uint256 orderId, string reason)",
  "function resolveDispute(uint256 orderId, string resolution, bool refundBuyer)",

  // Platform Stats
  "function getPlatformStats() view returns (uint256 totalShops, uint256 totalProducts, uint256 totalOrders, uint256 totalVolume, uint256 totalReviews)",

  // Events
  "event ShopRegistered(address indexed owner, uint256 indexed shopId, string shopName, uint256 timestamp)",
  "event ShopUpdated(address indexed owner, uint256 indexed shopId, uint256 timestamp)",
  "event ShopSuspended(uint256 indexed shopId, string reason, uint256 timestamp)",
  "event ShopReactivated(uint256 indexed shopId, uint256 timestamp)",
  "event ProductListed(uint256 indexed productId, uint256 indexed shopId, string name, uint256 price, uint256 timestamp)",
  "event ProductUpdated(uint256 indexed productId, uint256 timestamp)",
  "event ProductStatusChanged(uint256 indexed productId, uint8 newStatus, uint256 timestamp)",
  "event OrderCreated(uint256 indexed orderId, address indexed buyer, uint256 indexed shopId, uint256 totalAmount, uint256 timestamp)",
  "event OrderStatusUpdated(uint256 indexed orderId, uint8 newStatus, uint256 timestamp)",
  "event OrderRefunded(uint256 indexed orderId, uint256 amount, string reason, uint256 timestamp)",
  "event ReviewSubmitted(uint256 indexed productId, address indexed reviewer, uint256 rating, uint256 timestamp)",
  "event ProductAddedToWishlist(address indexed user, uint256 indexed productId, uint256 timestamp)",
  "event ProductRemovedFromWishlist(address indexed user, uint256 indexed productId, uint256 timestamp)",
  "event DisputeOpened(uint256 indexed orderId, address indexed opener, string reason, uint256 timestamp)",
  "event DisputeResolved(uint256 indexed orderId, string resolution, uint256 timestamp)",
] as const;

// ─── Module 018: Staking Pool ───
export const STAKING_POOL_ABI = [
  // Admin
  "function owner() view returns (address)",
  "function stakingToken() view returns (address)",
  "function earlyWithdrawPenaltyBps() view returns (uint256)",
  "function rewardBalance() view returns (uint256)",
  "function createPool(uint8 poolType, uint256 apyBps, uint256 minStake, uint256 maxStake, uint256 lockDays, uint256 maxCapacity) returns (uint256 poolId)",
  "function updatePool(uint256 poolId, uint256 newApyBps, bool active)",
  "function setEarlyWithdrawPenaltyBps(uint256 penaltyBps)",
  "function depositRewards(uint256 amount)",

  // Pool View
  "function getPool(uint256 poolId) view returns (uint8 poolType, uint256 apyBps, uint256 minStake, uint256 maxStake, uint256 lockDays, uint256 totalStaked, uint256 totalStakers, uint256 maxCapacity, bool active, uint256 createdAt)",
  "function getTotalPools() view returns (uint256)",

  // Staking Actions
  "function stake(uint256 poolId, uint256 amount) returns (uint256 stakeId)",
  "function unstake(uint256 stakeId)",
  "function claimRewards(uint256 stakeId)",
  "function compound(uint256 stakeId)",
  "function emergencyWithdraw(uint256 stakeId)",

  // Stake View
  "function getStakeInfo(uint256 stakeId) view returns (address staker, uint256 poolId, uint256 principal, uint256 pendingReward, uint256 stakedAt, uint256 unlockAt, uint256 lastClaimAt, uint8 status)",
  "function getUserStakes(address user) view returns (uint256[])",
  "function getTotalStakes() view returns (uint256)",
  "function getPendingReward(uint256 stakeId) view returns (uint256)",

  // Platform Stats
  "function getPlatformStats() view returns (uint256 totalPools, uint256 totalStaked, uint256 totalStakers, uint256 totalRewardsPaid, uint256 rewardBalance)",

  // Events
  "event PoolCreated(uint256 indexed poolId, uint8 poolType, uint256 apy, uint256 minStake, uint256 lockDays, uint256 timestamp)",
  "event PoolUpdated(uint256 indexed poolId, uint256 newApy, bool active, uint256 timestamp)",
  "event Staked(address indexed user, uint256 indexed poolId, uint256 indexed stakeId, uint256 amount, uint256 timestamp)",
  "event Unstaked(address indexed user, uint256 indexed stakeId, uint256 principal, uint256 reward, uint256 timestamp)",
  "event RewardsClaimed(address indexed user, uint256 indexed stakeId, uint256 reward, uint256 timestamp)",
  "event Compounded(address indexed user, uint256 indexed stakeId, uint256 reward, uint256 newPrincipal, uint256 timestamp)",
  "event EmergencyWithdraw(address indexed user, uint256 indexed stakeId, uint256 amount, uint256 penalty, uint256 timestamp)",
  "event RewardsDeposited(address indexed depositor, uint256 amount, uint256 timestamp)",
] as const;

export const FUNDRAISING_ABI = [
  // Admin
  "function owner() view returns (address)",
  "function paymentToken() view returns (address)",
  "function platformFeeBps() view returns (uint256)",
  "function matchingFundBalance() view returns (uint256)",
  "function setPlatformFeeBps(uint256 feeBps)",
  "function depositMatchingFund(uint256 amount)",
  "function applyMatchingFund(uint256 campaignId, uint256 matchAmount)",
  "function withdrawPlatformFees(uint256 amount)",

  // Campaign Management
  "function createCampaign(string title, string description, string imageURI, uint8 category, uint256 goalAmount, uint256 durationDays, uint256 minDonation) returns (uint256 campaignId)",
  "function updateCampaign(uint256 campaignId, string newDescription, string newImageURI)",
  "function cancelCampaign(uint256 campaignId)",

  // Milestones
  "function addMilestone(uint256 campaignId, string description, uint256 targetAmount)",
  "function completeMilestone(uint256 campaignId, uint256 milestoneIndex)",

  // Donations
  "function donate(uint256 campaignId, uint256 amount, string message)",

  // Withdraw / Refund
  "function withdrawFunds(uint256 campaignId)",
  "function claimRefund(uint256 campaignId)",

  // Views
  "function getCampaign(uint256 campaignId) view returns (address creator, string title, string description, string imageURI, uint8 category, uint256 goalAmount, uint256 raisedAmount, uint256 donorCount, uint256 deadline, uint256 minDonation, uint8 status, uint256 createdAt)",
  "function getTotalCampaigns() view returns (uint256)",
  "function getUserCampaigns(address user) view returns (uint256[])",
  "function getUserDonations(address user) view returns (uint256[])",
  "function getDonation(uint256 campaignId, address donor) view returns (uint256 amount, string lastMessage, uint256 lastDonatedAt)",
  "function getCampaignDonors(uint256 campaignId) view returns (address[])",
  "function getMilestones(uint256 campaignId) view returns (string[] descriptions, uint256[] targets, bool[] completed)",
  "function getPlatformStats() view returns (uint256 totalCampaigns, uint256 totalRaised, uint256 totalDonors, uint256 totalSuccessful, uint256 matchingFundBalance)",

  // Events
  "event CampaignCreated(uint256 indexed campaignId, address indexed creator, string title, uint256 goalAmount, uint256 deadline, uint256 timestamp)",
  "event CampaignUpdated(uint256 indexed campaignId, string newDescription, uint256 timestamp)",
  "event CampaignCancelled(uint256 indexed campaignId, uint256 timestamp)",
  "event DonationMade(uint256 indexed campaignId, address indexed donor, uint256 amount, string message, uint256 timestamp)",
  "event FundsWithdrawn(uint256 indexed campaignId, address indexed creator, uint256 amount, uint256 timestamp)",
  "event RefundClaimed(uint256 indexed campaignId, address indexed donor, uint256 amount, uint256 timestamp)",
  "event MatchingFundDeposited(address indexed depositor, uint256 amount, uint256 timestamp)",
  "event MatchingFundApplied(uint256 indexed campaignId, uint256 matchedAmount, uint256 timestamp)",
  "event MilestoneAdded(uint256 indexed campaignId, uint256 milestoneIndex, string description, uint256 targetAmount, uint256 timestamp)",
  "event MilestoneCompleted(uint256 indexed campaignId, uint256 milestoneIndex, uint256 timestamp)",
] as const;
