// ─── VNDC Campus Contract ABIs ───
// Minimal ABIs with only the functions needed for frontend interaction

export const VNDC_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "function burn(uint256 amount)",
  "function burnFrom(address account, uint256 amount)",
  "function pause()",
  "function unpause()",
  "function isPaused() view returns (bool)",
  "function isMinter(address account) view returns (bool)",
  "function isBurner(address account) view returns (bool)",
  "function addMinter(address account)",
  "function removeMinter(address account)",
  "function addBurner(address account)",
  "function removeBurner(address account)",
  "function getTokenInfo() view returns (string name, string symbol, uint8 decimals, uint256 totalSupply)",
  "function permit(address owner, address spender, uint256 amount, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event TokenMinted(address indexed to, uint256 amount)",
  "event TokenBurned(address indexed from, uint256 amount)",
  "event MinterAdded(address indexed account)",
  "event MinterRemoved(address indexed account)",
] as const;

export const REGISTRY_ABI = [
  "function registerUser(address user, string name, bytes32 role)",
  "function updateProfile(address user, string newName, string metadataUri)",
  "function getUserProfile(address user) view returns (tuple(address userAddress, string name, bytes32 role, string metadataUri, uint256 registeredAt, bool exists))",
  "function userExists(address user) view returns (bool)",
  "function getUserRole(address user) view returns (bytes32)",
  "function getUserName(address user) view returns (string)",
  "function changeUserRole(address user, bytes32 newRole)",
  "function getUsersByRole(bytes32 role) view returns (address[])",
  "function getRoleMemberCount(bytes32 role) view returns (uint256)",
  "function getTotalUsers() view returns (uint256)",
  "function getAllUsers() view returns (address[])",
  "function registerUsersBatch(address[] users, string[] names, bytes32[] roles)",
  "function getRegistryStats() view returns (uint256 totalUsers, uint256 totalAdmins, uint256 totalTeachers, uint256 totalStudents)",
  "event UserRegistered(address indexed user, bytes32 role)",
  "event UserUpdated(address indexed user, string newName)",
  "event UserRoleChanged(address indexed user, bytes32 oldRole, bytes32 newRole)",
] as const;

export const ACCESS_CONTROL_ABI = [
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function grantRole(bytes32 role, address account)",
  "function revokeRole(bytes32 role, address account)",
  "function isAuthorized(address account) view returns (bool)",
  "function getRoles(address account) view returns (bytes32[])",
  "function getRoleMembers(bytes32 role) view returns (address[])",
  "function getRoleMemberCount(bytes32 role) view returns (uint256)",
  "function isAdmin(address account) view returns (bool)",
  "function isTeacher(address account) view returns (bool)",
  "function isStudent(address account) view returns (bool)",
  "function isMerchant(address account) view returns (bool)",
  "function isIssuer(address account) view returns (bool)",
  "function grantRoleBatch(bytes32 role, address[] accounts)",
  "function revokeRoleBatch(bytes32 role, address[] accounts)",
  "function getAccessStats() view returns (uint256 adminCount, uint256 teacherCount, uint256 studentCount, uint256 merchantCount)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed grantedBy)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed revokedBy)",
] as const;

export const CREDENTIAL_VERIFICATION_ABI = [
  "function issueCredential(address student, string name, string level, uint256 expirationDays, string ipfsMetadata) returns (uint256 tokenId)",
  "function verifyCredential(uint256 tokenId) view returns (bool valid, string name, string level)",
  "function revokeCredential(uint256 tokenId)",
  "function getCredentialsByUser(address user) view returns (uint256[])",
  "function getCredential(uint256 tokenId) view returns (tuple(string name, string level, address issuer, uint256 issuedAt, uint256 expiresAt, bool revoked, string ipfsMetadata))",
  "function isCredentialValid(uint256 tokenId) view returns (bool)",
  "function addIssuer(address issuer)",
  "function removeIssuer(address issuer)",
  "function isIssuer(address issuer) view returns (bool)",
  "function getActiveCredentialsByUser(address user) view returns (uint256[])",
  "function getStats() view returns (uint256 totalIssuers, uint256 totalCredentialVariants)",
  "event CredentialIssued(uint256 indexed tokenId, address indexed student, string name, string level, address indexed issuer)",
  "event CredentialRevoked(uint256 indexed tokenId, address indexed revoker)",
] as const;

export const CREDENTIAL_NFT_ABI = [
  "function mint(address to, string credentialURI) returns (uint256)",
  "function burn(uint256 tokenId)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function tokensOfOwner(address owner) view returns (uint256[])",
  "function exists(uint256 tokenId) view returns (bool)",
  "function balanceOf(address owner) view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
] as const;

export const ACADEMIC_REWARD_ABI = [
  "function setRewardTier(uint256 tierId, string name, uint256 minGPA, uint256 vncdAmount, uint256 badgeTokenId)",
  "function awardStudent(address student, uint256 gpa) returns (uint256 rewardId)",
  "function claimReward(uint256 rewardId)",
  "function getStudentRewards(address student) view returns (uint256[])",
  "function getReward(uint256 rewardId) view returns (tuple(address student, uint256 gpa, uint256 tierId, uint256 issuedAt, bool claimed))",
  "function getRewardTier(uint256 tierId) view returns (tuple(string name, uint256 minGPA, uint256 vncdAmount, uint256 badgeTokenId, bool active))",
  "function deactivateTier(uint256 tierId)",
  "function getClaimedRewards(address student) view returns (uint256[])",
  "function getStats() view returns (uint256 totalAwarded, uint256 totalClaimed)",
  "function addIssuer(address issuer)",
  "function removeIssuer(address issuer)",
  "function isIssuer(address issuer) view returns (bool)",
  "event RewardTierSet(uint256 indexed tierId, string name, uint256 minGPA, uint256 vncdAmount)",
  "event StudentAwarded(uint256 indexed rewardId, address indexed student, uint256 gpa, uint256 tierId)",
  "event RewardClaimed(uint256 indexed rewardId, address indexed student)",
] as const;

export const ACADEMIC_BADGE_NFT_ABI = [
  "function mint(address to, uint256 badgeId, uint256 amount)",
  "function burn(address account, uint256 badgeId, uint256 amount)",
  "function getBalances(address account) view returns (uint256[])",
  "function createBadge(string uri) returns (uint256 badgeId)",
  "function uri(uint256 badgeId) view returns (string)",
  "function badgeExists(uint256 badgeId) view returns (bool)",
  "function hasBadge(address user, uint256 badgeId) view returns (bool)",
  "function balanceOf(address account, uint256 id) view returns (uint256)",
] as const;

export const PAYMENT_PROCESSOR_ABI = [
  "function processPayment(address merchant, uint256 amount, string paymentMethod) returns (uint256 paymentId)",
  "function refundPayment(uint256 paymentId, string reason)",
  "function linkWallet(string paymentMethod, string walletId)",
  "function unlinkWallet(string paymentMethod)",
  "function addPaymentMethod(string name, address tokenAddress, uint256 minAmount, uint256 maxAmount)",
  "function removePaymentMethod(string paymentMethod)",
  "function getPaymentRecord(uint256 paymentId) view returns (tuple(uint256 paymentId, address student, address merchant, uint256 amount, string paymentMethod, uint256 timestamp, bool isRefunded, uint256 refundAmount, string refundReason, uint256 refundTimestamp))",
  "function getStudentPayments(address student) view returns (tuple(uint256 paymentId, address student, address merchant, uint256 amount, string paymentMethod, uint256 timestamp, bool isRefunded, uint256 refundAmount, string refundReason, uint256 refundTimestamp)[])",
  "function getMerchantPayments(address merchant) view returns (tuple(uint256 paymentId, address student, address merchant, uint256 amount, string paymentMethod, uint256 timestamp, bool isRefunded, uint256 refundAmount, string refundReason, uint256 refundTimestamp)[])",
  "function isPaymentMethodSupported(string paymentMethod) view returns (bool)",
  "function getTotalStudentPayments(address student) view returns (uint256)",
  "function getTotalMerchantRevenue(address merchant) view returns (uint256)",
  "function getTotalPaymentCount() view returns (uint256)",
  "event PaymentProcessed(uint256 indexed paymentId, address indexed student, address indexed merchant, uint256 amount, string paymentMethod, uint256 timestamp)",
  "event PaymentRefunded(uint256 indexed paymentId, address indexed student, uint256 refundAmount, string reason, uint256 timestamp)",
] as const;

export const MERCHANT_REGISTRY_ABI = [
  "function registerMerchant(string name, string category, string contactEmail, string contactPhone) returns (address)",
  "function updateMerchant(address merchant, string name, string category, string contactEmail, string contactPhone)",
  "function approveMerchant(address merchant)",
  "function rejectMerchant(address merchant, string reason)",
  "function deactivateMerchant(address merchant)",
  "function reactivateMerchant(address merchant)",
  "function setCommissionRate(address merchant, uint256 commissionRate)",
  "function getMerchant(address merchant) view returns (tuple(address merchantAddress, string name, string category, string contactEmail, string contactPhone, bool isApproved, bool isActive, uint256 commissionRate, uint256 totalTransactions, uint256 totalRevenue, uint256 registrationDate, uint256 approvalDate))",
  "function isApprovedMerchant(address merchant) view returns (bool)",
  "function isMerchantActive(address merchant) view returns (bool)",
  "function getTotalMerchants() view returns (uint256)",
  "function getTotalApprovedMerchants() view returns (uint256)",
  "event MerchantRegistered(address indexed merchant, string name, string category, uint256 timestamp)",
  "event MerchantApproved(address indexed merchant, uint256 timestamp)",
] as const;

export const STUDENT_RECORD_MANAGER_ABI = [
  "function createRecord(string name, string studentId, string transcript) returns (uint256 recordId)",
  "function addGrade(uint256 recordId, string subject, uint256 grade, uint256 credits)",
  "function completeSemester(uint256 recordId, uint256 semesterIndex)",
  "function verifyRecord(uint256 recordId)",
  "function issueTranscript(uint256 recordId, string ipfsHash)",
  "function updateRecord(uint256 recordId, string name, string transcript)",
  "function getRecord(uint256 recordId) view returns (tuple(uint256 recordId, address student, string name, string studentId, uint256 enrollmentDate, uint256 totalCredits, uint256 cumulativeGpa, tuple(uint256 semesterIndex, tuple(string subject, uint256 grade, uint256 credits, uint256 timestamp)[] grades, uint256 gpa, uint256 totalCredits, uint256 timestamp, bool isCompleted)[] semesters, bool isVerified, address verifier, uint256 verificationDate, string transcriptIPFS))",
  "function getStudentRecords(address student) view returns (uint256[])",
  "function getSemesterGPA(uint256 recordId, uint256 semesterIndex) view returns (uint256)",
  "function getCumulativeGPA(uint256 recordId) view returns (uint256)",
  "function isRecordVerified(uint256 recordId) view returns (bool)",
  "function getTotalCredits(uint256 recordId) view returns (uint256)",
  "function getTotalRecords() view returns (uint256)",
  "function authorizeVerifier(address verifier)",
  "function revokeVerifier(address verifier)",
  "function isAuthorizedVerifier(address verifier) view returns (bool)",
  "event RecordCreated(address indexed student, uint256 recordId, string transcript, uint256 timestamp)",
  "event GradeAdded(address indexed student, uint256 recordId, string subject, uint256 grade, uint256 credits, uint256 timestamp)",
  "event SemesterCompleted(address indexed student, uint256 recordId, uint256 semesterIndex, uint256 gpa, uint256 timestamp)",
  "event RecordVerified(address indexed student, uint256 recordId, address verifier, uint256 timestamp)",
] as const;

export const STUDENT_DAO_ABI = [
  "function createProposal(string title, string description, string proposalType, bytes callData) returns (uint256 proposalId)",
  "function vote(uint256 proposalId, bool support)",
  "function executeProposal(uint256 proposalId)",
  "function cancelProposal(uint256 proposalId)",
  "function addMember(address member, uint256 votingPower)",
  "function removeMember(address member)",
  "function updateVotingPower(address member, uint256 newVotingPower)",
  "function setVotingPeriod(uint256 durationInSeconds)",
  "function setQuorum(uint256 quorumPercentage)",
  "function getProposal(uint256 proposalId) view returns (tuple(uint256 proposalId, address proposer, string title, string description, uint256 createdAt, uint256 votesFor, uint256 votesAgainst, bool executed, bool cancelled, uint256 votingEndTime, string proposalType, bytes callData))",
  "function getMember(address member) view returns (tuple(address memberAddress, uint256 votingPower, uint256 joinDate, bool isActive, uint256 proposalsCreated, uint256 votesParticipated))",
  "function isMember(address member) view returns (bool)",
  "function getVotingPower(address member) view returns (uint256)",
  "function hasVoted(uint256 proposalId, address member) view returns (bool)",
  "function getTotalMembers() view returns (uint256)",
  "function getTotalProposals() view returns (uint256)",
  "function getVotingPeriod() view returns (uint256)",
  "function isProposalApproved(uint256 proposalId) view returns (bool)",
  "function getTotalVotingPower() view returns (uint256)",
  "function getActiveProposals() view returns (uint256[])",
  "function getProposalVotes(uint256 proposalId) view returns (uint256 votesFor, uint256 votesAgainst)",
  "event ProposalCreated(uint256 indexed proposalId, address indexed proposer, string title, string description, uint256 timestamp)",
  "event Voted(uint256 indexed proposalId, address indexed voter, bool support, uint256 weight)",
  "event ProposalExecuted(uint256 indexed proposalId, uint256 timestamp)",
  "event ProposalCancelled(uint256 indexed proposalId, uint256 timestamp)",
  "event MemberJoined(address indexed member, uint256 votingPower, uint256 timestamp)",
] as const;

export const GOVERNANCE_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "function delegate(address delegatee)",
  "function delegates(address account) view returns (address)",
  "function getVotes(address account) view returns (uint256)",
  "function bulkMint(address[] recipients, uint256[] amounts)",
] as const;

export const STUDENT_ID_ABI = [
  "function issueStudentID(address student, string studentName, string program, uint256 enrollmentDate, string metadataURI) returns (uint256 tokenId)",
  "function suspendStudentID(uint256 tokenId, string reason)",
  "function revokeStudentID(uint256 tokenId, string reason)",
  "function reactivateStudentID(uint256 tokenId)",
  "function updateMetadataURI(uint256 tokenId, string newURI)",
  "function authorizeVerifier(address verifier)",
  "function revokeVerifier(address verifier)",
  "function getStudentInfo(uint256 tokenId) view returns (address studentAddr, string studentName, string program, uint256 enrollmentDate, uint256 issuedAt, bool isSuspended, bool isRevoked)",
  "function getStudentIDDetails(uint256 tokenId) view returns (string metadataURI, string suspensionReason, string revocationReason)",
  "function getActiveStudentIDs(address student) view returns (uint256[])",
  "function isActiveStudentID(uint256 tokenId) view returns (bool)",
  "function isAuthorizedVerifier(address verifier) view returns (bool)",
  "function getTotalStudentIDs() view returns (uint256)",
  "function getTotalActiveStudentIDs() view returns (uint256)",
  "function getTotalSuspendedStudentIDs() view returns (uint256)",
  "function getTotalRevokedStudentIDs() view returns (uint256)",
  "function balanceOf(address owner) view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "event StudentIDIssued(address indexed student, uint256 indexed tokenId, uint256 issuedAt)",
  "event StudentIDSuspended(uint256 indexed tokenId, string reason, uint256 suspendedAt)",
  "event StudentIDRevoked(uint256 indexed tokenId, string reason, uint256 revokedAt)",
  "event StudentIDReactivated(uint256 indexed tokenId, uint256 reactivatedAt)",
] as const;

export const SCHOLARSHIP_MANAGER_ABI = [
  "function createScholarship(string name, string description, uint256 totalAmount, uint256 maxAwards, string requirements, uint256 duration) returns (uint256)",
  "function depositFunds(uint256 scholarshipId, uint256 amount)",
  "function awardScholarship(uint256 scholarshipId, address student, uint256 amount)",
  "function claimScholarship(uint256 scholarshipId)",
  "function updateScholarshipStatus(uint256 scholarshipId, string newStatus)",
  "function withdrawFunds(uint256 scholarshipId, uint256 amount)",
  "function addFundingEntity(address fundingEntity)",
  "function removeFundingEntity(address fundingEntity)",
  "function getScholarshipInfo(uint256 scholarshipId) view returns (string name, string description, address funder, uint256 totalAmount, uint256 distributedAmount, uint256 maxAwards, uint256 awardsGiven, uint256 createdAt, uint256 endsAt, string status)",
  "function getScholarshipRequirements(uint256 scholarshipId) view returns (string)",
  "function getStudentScholarships(address student) view returns (uint256[])",
  "function isScholarshipOpen(uint256 scholarshipId) view returns (bool)",
  "function getTotalScholarships() view returns (uint256)",
  "function getTotalFundsInScholarships() view returns (uint256)",
  "function getTotalFundsDistributed() view returns (uint256)",
  "function getAvailableFunds(uint256 scholarshipId) view returns (uint256)",
  "event ScholarshipCreated(uint256 indexed scholarshipId, string name, uint256 totalAmount, uint256 maxAwards, address funder)",
  "event StudentAwarded(uint256 indexed scholarshipId, address indexed student, uint256 amount, uint256 awardedAt)",
  "event ScholarshipClaimed(uint256 indexed scholarshipId, address indexed student, uint256 amount, uint256 claimedAt)",
] as const;

export const JOB_BOARD_ABI = [
  "function registerEmployer(string companyName, string companyURI)",
  "function postJob(string title, string description, string category, string location, string jobType, uint256 minSalary, uint256 maxSalary, string requiredSkills) returns (uint256 jobId)",
  "function applyForJob(uint256 jobId, string coverLetter) returns (uint256 applicationId)",
  "function updateApplicationStatus(uint256 applicationId, string status)",
  "function updateJobStatus(uint256 jobId, string status)",
  "function submitReview(uint256 jobId, uint256 rating, string comment)",
  "function getJobDetails(uint256 jobId) view returns (string title, string description, address employer, string category, string location, string jobType, uint256 minSalary, uint256 maxSalary, string requiredSkills, string status, uint256 postedAt, uint256 applicationCount)",
  "function getApplicationDetails(uint256 applicationId) view returns (address applicant, uint256 jobId, string coverLetter, string status, uint256 submittedAt)",
  "function getEmployerInfo(address employer) view returns (string companyName, string companyURI, uint256 jobsPosted, uint256 registeredAt)",
  "function getJobApplications(uint256 jobId) view returns (uint256[])",
  "function getStudentApplications(address student) view returns (uint256[])",
  "function getEmployerJobs(address employer) view returns (uint256[])",
  "function isRegisteredEmployer(address employer) view returns (bool)",
  "function getTotalJobsPosted() view returns (uint256)",
  "function getTotalApplications() view returns (uint256)",
  "function getTotalEmployers() view returns (uint256)",
  "function getJobsByCategory(string category) view returns (uint256[])",
  "event JobPosted(uint256 indexed jobId, string title, address indexed employer, uint256 postedAt)",
  "event ApplicationSubmitted(uint256 indexed jobId, address indexed applicant, uint256 applicationId, uint256 submittedAt)",
  "event ApplicationStatusUpdated(uint256 indexed applicationId, string status)",
] as const;

export const EXTRACURRICULAR_REWARD_ABI = [
  "function registerActivity(string name, uint256 rewardAmount)",
  "function logActivity(address student, uint256 activityId)",
  "function claimActivityReward(uint256 activityId)",
  "event ActivityRegistered(uint256 indexed activityId, string name, uint256 rewardAmount)",
  "event ActivityLogged(address indexed student, uint256 indexed activityId)",
  "event ActivityRewardClaimed(address indexed student, uint256 indexed activityId)",
] as const;

export const CERTIFICATION_SYSTEM_ABI = [
  "function issueCertificate(address student, uint256 certId, uint256 amount, string uri)",
  "function batchIssueCertificates(address[] students, uint256 certId, uint256[] amounts)",
  "function revokeCertificate(address student, uint256 certId, uint256 amount)",
  "function getCertificateBalance(address student, uint256 certId) view returns (uint256)",
  "function uri(uint256 certId) view returns (string)",
  "event CertificateIssued(uint256 indexed certId, address indexed student, uint256 amount)",
  "event CertificateRevoked(uint256 indexed certId, address indexed student, uint256 amount)",
] as const;

export const ALUMNI_REGISTRY_ABI = [
  "function registerAlumni(string name, uint256 graduationYear, string program)",
  "function updateProfile(string name, string contactInfo)",
  "function createEvent(string name, string description, uint256 date)",
  "function registerForMentorship(string expertise)",
  "function donate(uint256 amount)",
  "event AlumniRegistered(address indexed alumni, string name, uint256 graduationYear)",
  "event EventCreated(uint256 indexed eventId, string name, uint256 date)",
  "event MentorRegistered(address indexed mentor, string expertise)",
  "event DonationReceived(address indexed donor, uint256 amount)",
] as const;

export const REPUTATION_BADGE_ABI = [
  "function awardBadge(address student, uint256 badgeType, uint256 points)",
  "function getReputationScore(address student) view returns (uint256)",
  "function getTier(address student) view returns (uint256)",
  "function getLeaderboard(uint256 limit) view returns (address[] students, uint256[] scores)",
  "event BadgeAwarded(address indexed student, uint256 badgeType, uint256 points)",
  "event TierUpgraded(address indexed student, uint256 newTier)",
] as const;

export const INTERNSHIP_MANAGER_ABI = [
  "function createProgram(string title, string description, string company, uint256 duration, uint256 stipend) returns (uint256)",
  "function applyForInternship(uint256 programId, string resume) returns (uint256)",
  "function assignMentor(uint256 applicationId, address mentor)",
  "function updateProgress(uint256 applicationId, uint256 progress, string notes)",
  "function completeInternship(uint256 applicationId)",
  "function getProgram(uint256 programId) view returns (string title, string description, string company, uint256 duration, uint256 stipend, uint256 applicants)",
  "event ProgramCreated(uint256 indexed programId, string title, string company)",
  "event ApplicationSubmitted(uint256 indexed programId, address indexed applicant, uint256 applicationId)",
  "event MentorAssigned(uint256 indexed applicationId, address indexed mentor)",
  "event InternshipCompleted(uint256 indexed applicationId)",
] as const;

export const RESEARCH_PLATFORM_ABI = [
  "function createProject(string title, string description, string[] tags) returns (uint256)",
  "function addContributor(uint256 projectId, address contributor, string role)",
  "function publishResult(uint256 projectId, string ipfsHash)",
  "function fundProject(uint256 projectId, uint256 amount)",
  "function getProject(uint256 projectId) view returns (string title, string description, address lead, uint256 funding, uint256 contributors)",
  "event ProjectCreated(uint256 indexed projectId, string title, address indexed lead)",
  "event ContributorAdded(uint256 indexed projectId, address indexed contributor)",
  "event ResultPublished(uint256 indexed projectId, string ipfsHash)",
  "event ProjectFunded(uint256 indexed projectId, uint256 amount)",
] as const;

export const AUDITING_SYSTEM_ABI = [
  "function createAuditJob(address contractAddress, string scope) returns (uint256)",
  "function submitAuditReport(uint256 jobId, string reportHash, uint256 severity)",
  "function voteOnReport(uint256 jobId, bool approve)",
  "function getAuditJob(uint256 jobId) view returns (address contractAddr, string scope, uint256 auditorCount, bool finalized)",
  "event AuditJobCreated(uint256 indexed jobId, address indexed contractAddr)",
  "event ReportSubmitted(uint256 indexed jobId, address indexed auditor, string reportHash)",
  "event AuditFinalized(uint256 indexed jobId, bool approved)",
] as const;

export const ANALYTICS_DASHBOARD_ABI = [
  "function getSystemMetrics() view returns (uint256 totalUsers, uint256 totalTransactions, uint256 totalTokensCirculating)",
  "function getUserAnalytics(address user) view returns (uint256 transactions, uint256 credentials, uint256 reputation)",
  "function generateReport(string reportType) returns (uint256 reportId)",
  "event ReportGenerated(uint256 indexed reportId, string reportType, uint256 timestamp)",
] as const;

export const INTERNAL_EXCHANGE_ABI = [
  "function createOrder(bool isBuyOrder, address tokenOffer, address tokenWant, uint256 amountOffer, uint256 amountWant) returns (uint256 orderId)",
  "function cancelOrder(uint256 orderId)",
  "function fillOrder(uint256 orderId, uint256 amount)",
  "function getOrder(uint256 orderId) view returns (uint256 id, address trader, bool isBuyOrder, address tokenOffer, address tokenWant, uint256 amountOffer, uint256 amountWant, uint256 filled, uint8 status, uint256 createdAt)",
  "function getOpenOrders() view returns (uint256[])",
  "function getUserOrders(address user) view returns (uint256[])",
  "function getOrderBook(address tokenA, address tokenB) view returns (uint256[] buyOrders, uint256[] sellOrders)",
  "function getTradingPair(address tokenA, address tokenB) view returns (uint256 lastPrice, uint256 volume24h, uint256 totalTrades)",
  "function createListing(string title, string description, string category, uint256 price, address paymentToken) returns (uint256 listingId)",
  "function buyListing(uint256 listingId)",
  "function cancelListing(uint256 listingId)",
  "function getListing(uint256 listingId) view returns (address seller, string title, string description, string category, uint256 price, address paymentToken, uint8 status, uint256 createdAt)",
  "function getActiveListings() view returns (uint256[])",
  "function getListingsByCategory(string category) view returns (uint256[])",
  "function getUserListings(address user) view returns (uint256[])",
  "function getTotalOrders() view returns (uint256)",
  "function getTotalListings() view returns (uint256)",
  "function getTotalVolume() view returns (uint256)",
  "event OrderCreated(uint256 indexed orderId, address indexed trader, bool isBuyOrder, address tokenOffer, address tokenWant, uint256 amountOffer, uint256 amountWant)",
  "event OrderFilled(uint256 indexed orderId, address indexed filler, uint256 amount)",
  "event OrderCancelled(uint256 indexed orderId)",
  "event ListingCreated(uint256 indexed listingId, address indexed seller, string title, uint256 price)",
  "event ListingPurchased(uint256 indexed listingId, address indexed buyer, uint256 price)",
  "event ListingCancelled(uint256 indexed listingId)",
] as const;
